name: 'ssh'
description: 'ssh into a server'
inputs:
  host:
    description: 'host of server'
    required: true
  username:
    description: 'user to login to server with'
    required: true
  key:
    description: 'ssh private key to use to login to server with'
    required: true
  local_files:
    description: 'local files to push up to your server'
    required: true
  remote_location:
    description: 'remote location to store your files at'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
